export const MESH_COLOR = 0xffffff;
export const LIGHT_COLOR = 0xffffff;
export const IMAGES_Y_OFFSET = 0.14;
export const MIN_CAMERA_DISTANCE = 1.5;
export const MAX_CAMERA_DISTANCE = 2.9;
export const ZOOM_TRIGGER_DISTANCE = 0.02;
export const POINT_LIGHT_MAX_INTENSITY = 28;
export const POINT_LIGHT_MIN_INTENSITY = 4.5;
export const LIGHT_CHANGE_FACTOR = (POINT_LIGHT_MAX_INTENSITY - POINT_LIGHT_MIN_INTENSITY)
    / ((MAX_CAMERA_DISTANCE - MIN_CAMERA_DISTANCE) / ZOOM_TRIGGER_DISTANCE);
